# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170630_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
